baseURL = 'https://inugasky.me'

title = "Inugasky's Blog"
theme = 'PaperMod'

[params]
defaultTheme = "light"

[params.assets]
favicon = "/images/avatar.png"
# favicon16x16 = "/images/avatar.png"
# favicon32x32 = "/images/avatar.png"
# apple_touch_icon = "/images/avatar.png"
# safari_pinned_tab = "/images/avatar.png"

[params.homeInfoParams]
Title = "いぬが好きー U・ᴥ・U"
Content = "セキュリティのお話など"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/taise-hub"
